<template>
<div class="Orders">
  <div v-show="this.item._id"
       class="row justify-content-right">
    <div class="col">
      <b-btn variant="danger"
             size="sm"
             class="float-right"
             @click="remove">Delete&nbsp;<i class="fas fa-trash-alt"></i></b-btn>
    </div>
  </div>
  <div class="row justify-content-left">
    <div class="col-12 col-sm-8 col-md-6 col-lg-6 mt-3">
      <OrdersSelectKey label="Select an order to edit"
                      placeholder="Search by name (press ENTER)"
                      v-model="item._id"
                      @change="onItemSelected"></OrdersSelectKey>
    </div>
    <div class="col-12 col-sm-8 col-md-6 col-lg-6 mt-3">
      <label>Number</label>
      <input class="form-control d-block w-75"
             v-model="item.number" placeholder="(autogenerated)" disabled />
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 mt-3">
      <b-btn size="lg"
             class='SaveButton'
             @click="save()"
             variant="primary">Save</b-btn>
    </div>
  </div>
</div>

</template>

<script>
import { NotyConfirm } from '@/plugins/noty';
import { call } from '@/plugins/rpcApi';
import UsersSelectKey from '@/components/tmd/controls/UsersSelectKey';
import OrdersSelectKey from '@/components/tmd/controls/OrdersSelectKey';

export default {
  layout: 'app',
  name: 'Orders',
  props: [],
  fetch() {},
  data() {
    return {
      item: {}
    }
  },
  async asyncData() {
    return {}
  },
  computed: {

  },
  methods: {
    onItemSelected(item) {
      Object.assign(this.item, item)
    },
    clear(){
    	Object.assign(this.item, {
            _id: null,
            email: ''
          });
    },
    async remove() {
      if (!this.item._id) {
        return
      }
      if (await NotyConfirm('Confirm Delete?')) {
        let r = await call('removeRecord', {
          model: 'order',
          _id: this.item._id
        })
        if (r !== false) {
          console.info(r)
          this.clear();
        }
      }
    },
    async save() {
      try {
        let doc = await call('saveRecord', Object.assign({}, this.item, {
          model: 'order'
        }))
        console.info(doc);
        this.clear();
        this.$noty.info('Saved');
      } catch (err) {
        console.error(err)
        this.$noty.warning(err.message,{
        	killer:true,
        	timeout:false
        });
      }
    }
  },
  components: {
    UsersSelectKey,
    OrdersSelectKey
  },
  created() {},
  mounted() {}
}

</script>

<style lang="scss" scoped="">
.Orders {}
</style>
